/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fall2019.comp4980;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;

/**
 * @author John.
 * This class creates the JFrame GUI.
 */
public class PreviewImage extends javax.swing.JFrame {

    /**
     * The current X,Y location of the square that thinks there is a Johnny Depp image inside it
     */
    public int best_scanX = 0;
    public int best_scanY = 0;

    /**
     * the 650x650 image with noise
     */

    private BufferedImage img;

    /**
     * Creates new form Display
     */
    public PreviewImage(BufferedImage img) {

        //setTitle("Where's Johnny?");
        initComponents();

        this.img = img;

        /** Click anywhere inside the GUI to have it try another example immediately instead of waiting for the program
         to scan everything */
        addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                System.out.println("*");
                TestClass.skip = true;
            }

        });
    }

    /**
     * Draw the GUI
     */
    public void paint(Graphics g) {
        super.paint(g);

        g.drawImage(img, getInsets().right, getInsets().top, img.getWidth(), img.getHeight(), null);


        g.setColor(Color.YELLOW);
        g.drawRect(getInsets().right + best_scanX, getInsets().top + best_scanY, 100, 100);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
